import React, { useState } from 'react'
import { Layout } from '@/components/layout'
import Head from 'next/head'
import { motion } from 'framer-motion'
import { LoanCasesBody, LoanCasesCover } from '@/components/loancasesBlock'
import LOAN_CASES_DATA from '@/data/loan_cases.json'
import Link from 'next/link'

const CasesDynamicPage = () => {
  return (
    <>
      <Head>
        <title>攏山借貸案例</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <motion.section className="overflow-hidden text-primary mb-20"></motion.section>
          <section></section>
        </Layout>
      </main>
    </>
  )
}

export default CasesDynamicPage
