import React, { useEffect, useState } from 'react'
import { Layout } from '@/components/layout'
import Head from 'next/head'
import { motion } from 'framer-motion'
import { LoanCasesBody, LoanCasesCover } from '@/components/loancasesBlock'
import LOAN_CASES_DATA from '@/data/loan_cases.json'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useMouseStore } from '@/store'

export default function LoancasesPage() {
  const route = useRouter()

  // useEffect(() => {
  //   if (route.basePath.length === 0) return
  //   const reset = useMouseStore.getState().reset
  //   route.events.on('routeChangeStart', reset)
  //   return () => route.events.off('routeChangeStart', reset)
  // }, [route])

  return (
    <>
      <Head>
        <title>攏山借貸案例</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <motion.section className="overflow-hidden text-primary mb-20 max-lg:mb-0 max-sm:sticky max-sm:top-0 max-sm:z-0">
            <LoanCasesCover list={LOAN_CASES_DATA} />
          </motion.section>
          <section className="max-sm:relative z-10">
            <LoanCasesBody
              list={LOAN_CASES_DATA}
              length={LOAN_CASES_DATA.length}
              className="max-w-screen-xxl m-auto pt-20 pb-20 grid-cols-[repeat(3,minmax(0,_1fr))] bg-[rgba(255,255,255,0.8)] backdrop-blur px-5 max-lg:grid-cols-[repeat(2,minmax(0,_1fr))] max-sm:grid-cols-[repeat(1,minmax(0,_1fr))]"
            />
          </section>
        </Layout>
      </main>
    </>
  )
}
