import React, { useEffect, useState } from 'react'
import { Layout } from '@/components/layout'
import Head from 'next/head'
import { motion } from 'framer-motion'
import { LoanCasesBody, LoanCasesCover } from '@/components/loancasesBlock'
import LOAN_CASES_DATA from '@/data/loan_cases.json'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useMouseStore } from '@/store'

export default function LoancasesPage() {
  const [anEnd, setAnEnd] = useState(false)
  const route = useRouter()

  useEffect(() => {
    const reset = useMouseStore.getState().reset
    route.events.on('routeChangeStart', reset)
    return () => route.events.off('routeChangeStart', reset)
  }, [route])

  return (
    <>
      <Head>
        <title>攏山借貸案例</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <motion.section className="overflow-hidden text-primary mb-20">
            <LoanCasesCover list={LOAN_CASES_DATA} />
          </motion.section>
          <section>
            <LoanCasesBody
              list={LOAN_CASES_DATA}
              length={LOAN_CASES_DATA.length}
              className="px-40 py-40"
            />
          </section>
        </Layout>
      </main>
    </>
  )
}
