import Head from 'next/head'
import { Layout } from '@/components/layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <div className="min-h-screen">
            <section className="bg-primaryBlack text-primary text-sm p-2 flex">
              <span
                className="
                          cursor-pointer
                          m-auto 
                          relative 
                          after:content-['→']  
                          after:block 
                          after:absolute 
                          after:right-[-1.5rem]
                          after:w-5 
                          after:h-5 
                          after:top-0  
                          after:text-white
                          after:-translate-y-2
                          after:text-center
                          after:text-lg
                          "
              >
                了解更多最近快速成功借貸實例
              </span>
            </section>
          </div>
        </Layout>
      </main>
    </>
  )
}
