import Head from 'next/head'
import { Layout } from '@/components/layout'
import React, { useLayoutEffect, useEffect } from 'react'

import {
  MediaSection,
  HomePageSectionBody,
  TagLineSection,
  HomeAnimateProcessSection,
  HomeServicesSection,
  HomeProducts,
  HomePageCover,
} from '@/components/HomeBlock'

export default function Home() {
  // useEffect(() => {
  //   window.history.scrollRestoration = 'manual'
  // }, [])
  return (
    <>
      <Head>
        <title>攏山借貸</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen flex flex-col items-center">
        <Layout>
          <div className="h-[3.3rem] max-md:h-0" />
          <TagLineSection description="了解更多最近快速成功借貸實例" />
          <HomePageCover />
          <section>
            <div className="sticky top-[4rem]">
              <MediaSection />
            </div>
            <HomePageSectionBody />
          </section>
          <HomeAnimateProcessSection />
          <HomeServicesSection />
          <HomeProducts />
        </Layout>
      </main>
    </>
  )
}
