import React from 'react'
import { Layout } from '@/components/layout'
import Head from 'next/head'

export default function LoancasesPage() {
  return (
    <>
      <Head>
        <title>攏山借貸案例</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <section>
            <div className="pl-40 pr-40 text-black pt-40">
              <div>攏山借貸案例</div>
            </div>
          </section>
        </Layout>
      </main>
    </>
  )
}
