import React from 'react'
import { Layout } from '@/components/layout'
import Head from 'next/head'

export default function QuestionAndAnswerPage() {
  return (
    <>
      <Head>
        <title>攏山借貸相關問題</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <section>
            <div className="pl-40 pr-40 text-black pt-40 flex gap-5">
              <div className="flex-1">efowj</div>
              <div className="flex-1">
                <details className="">
                  <summary
                    id="question_and_answer"
                    className="w-full bg-primaryBlack text-white p-3"
                  >
                    房屋借貸
                  </summary>
                  <div className="ml-5">
                    <details>
                      <summary>房屋借貸</summary>
                      Something small enough to escape casual notice.
                    </details>
                    <details>
                      <summary>房屋借貸</summary>
                      Something small enough to escape casual notice.
                    </details>
                    <details>
                      <summary>房屋借貸</summary>
                      Something small enough to escape casual notice.
                    </details>
                  </div>
                </details>
              </div>
            </div>
          </section>
        </Layout>
      </main>
    </>
  )
}
