import React, { useCallback, useState, useEffect } from 'react'
import { Layout } from '@/components/layout'
import Head from 'next/head'
import SCAM_PREVENTION from '@/data/scam_prevention.json'
import { ScamPreventionPopup } from '@/components/popup'
import { AnimatePresence } from 'framer-motion'
import { ProductBlock } from '@/components/productBlock'
import PRODUCT_DATA from '@/data/product.json'

import {
  ScamPreventionHeader,
  ScamPreventionBox,
} from '@/components/scamPreventionBlock'
import { useAboutusStore } from '@/store'
import { shallow } from 'zustand/shallow'

type UpdatePopupFn = ({ show, index }: { show: boolean; index: number }) => void

export default function ScamPrevention() {
  const [{ show, index }, setPopup] = useState({ show: false, index: 0 })

  const { setCoverOnload } = useAboutusStore(
    (state) => ({
      setCoverOnload: state.setCoverOnLoad,
    }),
    shallow
  )

  const updatePopup: UpdatePopupFn = (popupContent) => {
    setPopup(popupContent)
    document.body.style.overflow = popupContent.show ? 'hidden' : 'scroll'
  }

  useEffect(() => {
    setCoverOnload(true)
    return () => setCoverOnload(false)
  }, [])

  return (
    <>
      <Head>
        <title>攏山防詐騙專區</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <section>
            <AnimatePresence>
              {show && (
                <ScamPreventionPopup
                  title={SCAM_PREVENTION[index].case.title}
                  caseContent={SCAM_PREVENTION[index].case.content}
                  close={() => updatePopup({ index: 0, show: false })}
                />
              )}
            </AnimatePresence>

            <div className="px-40 gap-5 pt-60 pb-40 grid grid-flow-row grid-cols-[repeat(4_,1fr)]">
              <ScamPreventionHeader
                title="害怕擔心受騙嗎?"
                subtitle="攏山告訴你不得不知的小技巧"
              />
              {SCAM_PREVENTION.map((item, index) => (
                <ScamPreventionBox
                  onClick={() => updatePopup({ show: true, index })}
                  key={`${item.id}_${item.title}`}
                  {...item}
                />
              ))}
            </div>
            <ProductBlock data={PRODUCT_DATA} />
          </section>
        </Layout>
      </main>
    </>
  )
}
