import Head from 'next/head'
import { Layout } from '@/components/layout'
import React, { useEffect } from 'react'

import {
  MediaSection,
  HomePageSectionBody,
  TagLineSection,
  HomeAnimateProcessSection,
  HomeServicesSection,
  HomeProducts,
  HomePageCover,
} from '@/components/HomeBlock'
import { useRouter } from 'next/router'

export default function Product() {
  const route = useRouter()
  const { product } = route.query

  return (
    <>
      <Head>
        <title>{product}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <p>{product}</p>
        </Layout>
      </main>
    </>
  )
}
