import Head from 'next/head'
import { Layout } from '@/components/layout'
import React, { useEffect } from 'react'
import { useRouter } from 'next/router'
import SERVICE_OFFERINGS_DATA from '@/data/service_offerings.json'
import Image from 'next/image'
import { LoopSwiper } from '@/components/swipper'

export default function Product() {
  const route = useRouter()

  const data = SERVICE_OFFERINGS_DATA.filter(
    (item) => item.slug === route.asPath
  )?.[0]

  if (!data) return null

  console.log(data)

  return (
    <>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-primary max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <div className="h-12 mt-1" />
          {/* <div className="py-5">
            <p className="text-gray-500 text-xl font-thin">
              <span className="p-2">{data.subtitle}</span>
              <span>-</span>
              <span className="p-2">{data.description}</span>
            </p>
          </div> */}

          <LoopSwiper
            one={`${data.subtitle} ${data.description}`}
            two={`${data.subtitle} ${data.description}`}
          />

          <section className="min-h-screen mx-10">
            <div className="p-10 bg-primary">
              <h1 className="text-7xl m-auto text-center font-bold">
                {data.title}
              </h1>
            </div>
            <div className="relative h-[80vh]  my-10 rounded-xl overflow-hidden">
              <Image
                src={data.imgUrl}
                className="object-cover"
                fill
                alt={data?.title}
                draggable={false}
                priority
              />
            </div>
          </section>
        </Layout>
      </main>
    </>
  )
}
