import Head from 'next/head'
import { Layout } from '@/components/layout'
import React from 'react'
import SERVICE_OFFERINGS_DATA from '@/data/service_offerings.json'
import * as uuid from 'uuid'
import { ServiceCard } from '@/components/card'
import { motion } from 'framer-motion'

export default function ServiceOfferings() {
  return (
    <>
      <Head>
        <title>攏山服務項目</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen-2xl mr-auto ml-auto shadow-body min-h-screen">
        <Layout>
          <div className="h-28 mb-2" />
          <motion.div className="mt-32 max-w-screen-xxl m-auto overflow-hidden">
            <motion.p
              animate={{ opacity: 1 }}
              initial={{ opacity: 0 }}
              transition={{ duration: 0.6, delay: 1 }}
              className="text-center"
            >
              最新內容
            </motion.p>
            <motion.h1
              animate={{ y: 0, opacity: 1 }}
              initial={{ y: 100, opacity: 0 }}
              transition={{ duration: 0.6, type: 'just' }}
              className="text-7xl font-bold text-center py-3 will-change-transform"
            >
              攏山服務項目
            </motion.h1>
            <motion.p
              transition={{ duration: 0.6, type: 'just', delay: 0.3 }}
              animate={{ rotateX: 0, scale: 1, opacity: 1 }}
              initial={{ rotateX: 100, scale: 1.2, opacity: 0 }}
              className="text-center w-fit m-auto mt-14 border p-2 will-change-transform"
              style={{ perspective: '1000px' }}
            >
              攏山是一家致力於協助有資金需求的客戶找到最合適的解決方案的公司
            </motion.p>
          </motion.div>
          <section className="py-20 max-w-screen-xxl m-auto">
            <div className="grid grid-cols-[repeat(4,_1fr)] gap-3 gap-y-6">
              {SERVICE_OFFERINGS_DATA.map((item) => (
                <ServiceCard key={uuid.v4()} {...item} />
              ))}
            </div>
          </section>
        </Layout>
      </main>
    </>
  )
}
